### ISSUE TITLE
Support for inline elements

### ISSUE THREAD

**Issue by hmdne** [metanorma/coradoc#31]
Coradoc doesn't support parsing of inline elements, for instance:

* styling (bold, italic)
* hyperlinks
* images

**Comment by webdev778** [comment]
To implement reverse_adoc in terms of Coradoc, we would need
to at least create dummy classes that will handle those inline elements. @ronaldtse

**Comment by ronaldtse** [comment]
@webdev778 yes we need to add all of these inline elements.

There are additional inline elements, see:
* https://www.metanorma.org/author/topics/inline_markup/text_formatting/

**Comment by ronaldtse** [comment]
Done.

**Comment by hmdne** [comment]
This issue is still a work in progress. This is just partially solved for now.
